mkdir -p .github/workflows
cat > .github/workflows/build.yml <<'YAML'
name: Build and push (amd64)
'on':
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/${{ github.repository }}:jazzy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE }}
YAML

# sanity check: ensure no tabs
! grep -nP '\t' .github/workflows/build.yml || true

git add .github/workflows/build.yml
git commit -m "Fix workflow YAML: quote 'on', proper indentation"
git push
