# from the repo root
mkdir -p .github/workflows

# create a clean file with UNIX line endings and no tabs/BOM
cat > .github/workflows/main.yml <<'YAML'
name: CI (sanity)
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "GitHub Actions YAML parsed OK"
YAML

# quick sanity checks
grep -nP '\t' .github/workflows/main.yml && echo "Found a TAB!" || echo "No tabs ✅"
file -b .github/workflows/main.yml    # should say "ASCII text" (no CRLF, no BOM)
sed -n '1,25p' .github/workflows/main.yml

# commit & push
git add .github/workflows/main.yml
git commit -m "Add minimal main.yml (no tabs/CRLF/BOM)"
git push
