name: build-driver
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-arch emulation)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Optional: login if you want to push to Docker Hub
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          load: true             # produce a local image on the runner (no push)
          tags: robotino-driver:jazzy
          build-args: |
            REC_RPC_URL=https://packages2.openrobotino.org/pool/buster/main/r/rec-rpc/rec-rpc_1.6.1_amd64.deb
            API2_URL=https://packages2.openrobotino.org/pool/buster/main/r/robotino-api2/robotino-api2_1.1.14_amd64.deb
            DAEMONS_URL=https://packages2.openrobotino.org/pool/buster/main/r/robotino-daemons/robotino-daemons_2.0.20_amd64.deb
            DEV_URL=https://packages2.openrobotino.org/pool/buster/main/r/robotino-dev/robotino-dev_1.0.3_amd64.deb

      # Optional: push to a registry instead of load
      # - name: Build & Push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     platforms: linux/amd64
      #     push: true
      #     tags: yourrepo/robotino-driver:jazzy
      #     build-args: |
      #       REC_RPC_URL=...
      #       API2_URL=...
      #       DAEMONS_URL=...
      #       DEV_URL=...
