# from your repo root
mkdir -p .github/workflows

cat > .github/workflows/docker.yml <<'YAML'
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "it works"
YAML
